### PR TITLE
Ruby gem install

### PR DESCRIPTION
**Pull request by athos-ribeiro**
The current regex is matching "gem install" inside comments. This commit fixes it. Also, I believe we could try matching %{gem_install} as well (in addition to the current check), which I can introduce in a new commit if desired.

### CODE REVIEW

**Comment by pypingou** [comment]
Looks like there is something wrong with your PR :)

**Comment by athos-ribeiro** [comment]
Yes, I tried pinging someone on irc but the fedora-review channel seems to be low on activity. I believe this is a mirror for https://git.fedorahosted.org/cgit/FedoraReview.git right? If not, then there is something wrong with the pull request.

I did the changes over what I believe to be upstream (fedorahosted repo?) since this (devel@github) seems to be outdated. If this is the case, someone may want to push the changes from the last 2 years to this branch (devel) before accepting this PR.

The other question is: is here the best place to submit patches for fedoraReview?

**Comment by pypingou** [comment]
Indeed, the github mirror seems to be quite outdated

> The other question is: is here the best place to submit patches for fedoraReview?

I think seeing how outdated the mirror is already partly answers your question, these days I see most activity happening on the trac instance at fedorahosted: https://fedorahosted.org/FedoraReview/

**Comment by athos-ribeiro** [comment]
devel branch was updated. I will close this PR and reopen it since github is not updating the comparisons at all.

**Pull request closed without merging**
